from sympy import Mod


# HELPER FUNCTION
def cyclic_subgroup(a, n):
    """Return the cyclic subgroup generated by a in Z_n."""
    subgroup = []
    k = 0
    current = Mod(0, n)

    while True:
        current = int(Mod(a * k, n))
        if current in subgroup:
            break
        subgroup.append(current)
        k += 1

    return subgroup


# Example: Z_16 and element 12
a = 12
n = 16
sub_group = cyclic_subgroup(a, n)

print(f"Cyclic subgroup ⟨{a}⟩ in Z_{n}: {sub_group}")
print(f"Order of the subgroup: {len(sub_group)}")
